runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()
syntax on
filetype plugin indent on

" Enable theme
syntax enable
set background=dark
colorscheme hybrid

" Use relative numbering instead of absolute
set relativenumber

" Change <Leader> to space
let mapleader=" "

" Change tabs to 4 spaces
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" Always have 5 lines above or below the cursor when scrolling
set scrolloff=5

" When minimizing a window make it as small as possible
set winminheight=0

" Always show the status line
set laststatus=2

" Dont use case-sensitive search (use smartcase when explicit case-sensitive is needed)
set ignorecase
set smartcase

" Fix my frequently wrong typed Wq (etc.) when quiting vim
command WQ wq
command Wq wq
command W w
command Q q

" Add shortcut for saving readonly files
command WW :execute ':silent w !sudo tee % > /dev/null' | :edit!

" Map F5 to list and select buffers
map <F5> :buffers<CR>:buffer<Space>

" Disable Arrow keys in normal, visual and select and operator pending mode (hjkl training)
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Disable Arrow keys in insert mode (hjkl training)
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Enable arrow window navigation in normal mode
nmap <up> <C-W>k
nmap <down> <C-W>j
nmap <left> <C-W>h
nmap <right> <C-W>l

" Enable (up/down) arrow window navigation with ALT key and make the current window
" fullscreen, minimalize the others
nmap <A-up> <C-W>k <C-W>_
nmap <A-down> <C-W>j <C-W>_

" Shorcut for making all windows equal sized
nmap <A-=> <C-W>=

" Create shortcut for Esc in insert mode (`^ makes sure the cursor stays at
" the same position as before the Esc)
imap jk <Esc>
imap kj <Esc>
inoremap <Esc> <Esc>`^

" Shortcut for easy navigating to begin/end of line
nmap aa ^
nmap ;; $

" NERDTree plugin
let NERDTreeShowHidden=1

" CtrlP plugin
let g:ctrlp_show_hidden = 1
