runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()
syntax on
filetype plugin indent on

" Use relative numbering instead of absolute
set relativenumber

" Change <Leader> to space
let mapleader=" "

" Always have 5 lines above or below the cursor when scrolling
set scrolloff=5

" Fix my frequently wrong typed Wq (etc.) when quiting vim
command WQ wq
command Wq wq
command W w
command Q q

" Add shortcut for saving readonly files
command WW :execute ':silent w !sudo tee % > /dev/null' | :edit!

" Map F5 to list and select buffers
nnoremap <F5> :buffers<CR>:buffer<Space>

" Disable Arrow keys in normal, visual and select and operator pending mode (hjkl training)
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Disable Arrow keys in insert mode (hjkl training)
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Create shortcut for Esc in insert mode
imap jk <esc>
imap kj <esc>

" Shortcut for easy navigating to begin/end of line
nmap aa ^
nmap ;; $
